### ISSUE TITLE
CSS画三角形、扇形、半圆形、椭圆形；

### ISSUE THREAD

**Issue by conan1992** [conan1992/mo#10]
### 三角形
```css
#test {
            position: fixed;
            top: 100px;
            left: 100px;
            cursor: pointer;
            border-width: 100px;
            border-style: solid;
            border-color: red transparent transparent transparent;
        }
```
```css
#test {
            width: 0;
            height: 0;
            border-left: 50px solid transparent;
            border-right: 50px solid transparent;
            border-bottom: 100px solid red;
        }
```
```css
#test {
            width: 0;
            height: 0;
            border-bottom: 100px solid red;
            border-right: 100px solid transparent;
        }
```
### 扇形
在三角形基础上加上border-radius=50
```css
/*扇形*/
.sector {
  width: 0;
  height: 0;
  border: 100px solid red;
  border-color: red transparent transparent transparent;
  border-radius: 50%;
}
/*或者*/
.sector {
  width: 100px;
  height: 100px;
  border: 100px solid transparent;
  border-top-color: red;
  box-sizing: border-box; /* 这步很重要 */
  border-radius: 50%;
}
```

### 半圆
border-radius:左上角，右上角，右下角，左下角
```css
#test {
            width: 100px;
            height: 100px;
            background-color: red;
            margin-top: 20px;
            height: 50px;
            border-radius: 0 0 50px 50px;
        }
```

### 椭圆
```css
#test {
            width: 100px;
            height: 100px;
            background-color: red;
            margin-top: 20px;
            height: 50px;
           border-radius: 50px/25px; /* x轴/y轴 */主要在于要理解水平半径和垂直半径：有斜杠，则斜杠前表示水平半径长度，斜杠后表示垂直半径高度；无斜杠，表示水平半径和垂直半径一样。
        }
```
### 参考
- [纯 CSS 实现绘制各种三角形（各种角度）](https://www.cnblogs.com/chengxs/p/11406278.html)
- [DD每周前端七题详解-第二期](https://juejin.im/post/5ed732dfe51d457879333878)
